
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
django = "^3.2.5"
django-rest-framework = "^0.1.0"
django-cors-headers = "^3.7.0"

[tool.pyflow.dev-dependencies]

