
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
django = "^3.2.5"
djangorestframework = "3.12.2"
django-cors-headers = "^3.7.0"
django-crispy-forms = "^1.12.0"
django-filter = "^2.4.0"

[tool.pyflow.dev-dependencies]

