
[tool.pyflow]
py_version = "3.9"
version = "0.1.0"
authors = ["HEKUCHAN <Heitorhirose@gmail.com>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
django = "^3.2.5"
djangorestframework = "3.12.2"
django-cors-headers = "^3.7.0"
django-filter = "^2.4.0"
black = "^21.7b0"
colorama = "^0.4.4"

[tool.pyflow.dev-dependencies]