# Generated by Django 3.2.6 on 2021-08-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_usertokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
