# Generated by Django 3.2.5 on 2021-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_career_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='EndWork',
            field=models.DateField(blank=True, null=True),
        ),
    ]
