# Generated by Django 3.2.5 on 2021-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_career_endwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='core.Tag'),
        ),
    ]
