# Generated by Django 3.2.6 on 2021-08-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usertokens_access_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
