# Generated by Django 3.2.5 on 2021-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_career_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='career_tags', to='core.Tag'),
        ),
    ]
