# Generated by Django 3.2.6 on 2021-08-12 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_career_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelikes',
            name='love',
        ),
        migrations.AddField(
            model_name='sitelikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitelikes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
