# Generated by Django 3.2.7 on 2021-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_loginlogging'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogging',
            name='locked_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
