# Generated by Django 3.2.7 on 2021-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loginlogging_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogging',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
