# Generated by Django 3.2.7 on 2021-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loginlogging_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogging',
            name='login_at',
            field=models.DateTimeField(),
        ),
    ]
